services:
  - type: web
    name: bhairavi-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MONGO_URI
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
